# Generated by Django 4.1.13 on 2024-11-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('environment', 'Environment'), ('community', 'Community')], default='community', max_length=100),
        ),
    ]
