# Generated by Django 4.1.13 on 2024-11-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, default='Not specified', max_length=255, null=True),
        ),
    ]
