# Generated by Django 4.1.13 on 2024-10-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_hours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicehour',
            name='date',
        ),
    ]
