# Generated by Django 4.1.13 on 2024-10-25 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_hours', '0002_remove_servicehour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehour',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 10, 25, 6, 15, 43, 614177, tzinfo=datetime.timezone.utc)),
        ),
    ]
