# Generated by Django 4.1.13 on 2024-11-21 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_hours', '0003_servicehour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehour',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 12, 1, 51, 994833, tzinfo=datetime.timezone.utc)),
        ),
    ]
